const nftTypes = {
  ADD_NEW_NFT_START: 'ADD_NEW_NFT_START',
  FETCH_NFTS_START: 'FETCH_NFTS_START',
  SET_NFTS: 'SET_NFTS',
  DELETE_NFT_START: 'DELETE_NFT_START',
  FETCH_NFT_START: 'FETCH_NFT_START',
  SET_NFT: 'SET_NFT',
};

export default nftTypes;